config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"

  get '/dashboard/producer/:producer_id', to: 'dashboard#show', as: :producer_dashboard
  get '/dashboard/designer/:designer_id', to: 'dashboard#show', as: :designer_dashboard

  get 'dashboard/payment_amount_popup'

  get '/states', to: 'addresses#get_states'
  post '/close_modal/:modal_id', to: 'modals#close', as: :close_modal

  resources :products, only: [:index, :show, :new, :create,:edit, :update] do
    delete 'remove_variant', on: :member
    get 'edit_producer', on: :member
    patch 'update_producer', on: :member
  end

  resources :orders do
    member do
      get :download
      get :confirm
      get :reject
      get :send_message
      post :message_create
      get :cancel_request
      post :update_cancel_status
      get :select_variant
      get :assignee
      post :assignee_create
      get :assignee_remove_confirmation
      delete :assigne_remove
      get :on_hold_popup
      get :in_production_popup
      get :rejected_popup
      get :fullfilled_popup
      get :delete_confirmation
      get :cancel_order
      get :new_cancel_request
      post :create_cancel_request
      get :update_priority
      get :request_revision
      patch :request_revision_update
      post :create_address
      post :order_update_shipping
      delete :remove_product
      delete :remove_product_image
      delete :remove_design_files
      get :set_dimensions
      post :update_dimensions
      get :update_job_price
      patch :assigne_update_price
      get :order_slip
      get :duplicate_order
      get :edit_sender
      post :update_sender
      delete :remove_shipo_lable
      get :download_shippo_label
      post :undo
      get :save_changes_confirmation
    end

    collection do
      get :add_new_product
      get :select_variant
      get :all_producer
      get :cancel_order_index
      get :new_order_product
      post :etsy_import
    end
  end

  resources :variants do
    get :inventory, on: :collection
    get :producer_inventory, on: :member
  end

  resources :producers_variants, only: [:edit, :update] do
    member do
      get :edit_inventory
      patch :update_inventory
    end
  end

  resources :producers, only: [:edit, :update] do
    post :request_payment, on: :member
    resources :producer_variant_histories, only: [:index]
  end

  resources :designers, only: [] do
    post :request_payment, on: :member
  end

  # Sessions routes
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/etsy/authorize', to: 'etsy#authorize'
  get '/etsy/callback', to: 'etsy#callback'

  resources :payments, only: [:new, :create] do
    get :export, on: :collection
  end

  namespace :admin do
    resources :orders, only: [:index] do
      collection do
        get :on_hold
        get :rejected
        get :in_production
        get :fulfilled
      end
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    if current_user.admin?
      @producers = Producer.all
      @designers = Designer.all
    end

    @user     = current_user
    @payments = @user.payments.paginate(page: params[:page], per_page: 9) unless @user.admin?
  end

  def show
    if params[:designer_id].present?
      @designer = Designer.find(params[:designer_id])
      @payments = @designer.payments.paginate(page: params[:page], per_page: 9)
    elsif params[:producer_id].present?
      @producer = Producer.find(params[:producer_id])
      @payments = @producer.payments.paginate(page: params[:page], per_page: 9)
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_designer_dashboard.html.erb
<div class="hero_wrapper">
  <%= render "shared/sidebar" %>
  <div class="designer_dasboard_wrapper">
    <div class="order_head">

      <div class="head_content">
        <%= link_to new_order_path , class: 'manual_btn' do %>
          <%= image_tag 'ic_plus', alt: 'icon', class: 'plus_icon' %>
          <span>Create Manual Order</span>
        <% end %>
          <%= render 'shared/profile_head' %>
      </div>
    </div>

    <div class="designer_name"><%= designer.name %></div>

    <div class="total_wrap">
      <div class="total_box">
        <div class="total_head">Total Orders Completed</div>
        <div class="total_count"><%= designer.no_of_orders_completed %></div>
      </div>
    </div>

    <div class="designer_name finance">Finance</div>
    <div class="total_wrap">
      <div class="total_box finance_box">
        <div class="total_head">Current Balance</div>
        <div class="total_count">$<%= format_number(designer.pending_payment.to_f.round(2)) %></div>
        <div class="group_text">
          <div class="group_content">
            <div class="text_head">Received Amount</div>
            <div class="text_data">$<%= format_number(designer.received_payment.to_f.round(2)) %></div>
          </div>
          <div class="group_content">
            <div class="text_head">Requested Amount</div>
            <div class="text_data">$<%= format_number(designer.requested_payment.to_f.round(2)) %></div>
          </div>
          <div class="group_content">
            <div class="text_head">Total Earned</div>
            <div class="text_data bold_text">$<%= format_number(designer.total_earned) %></div>
          </div>
        </div>

        <% if current_user.admin? && designer.has_requested_payment? %>
          <%= link_to new_payment_path(user_id: designer.id),
              class: 'request_btn',
              data: { turbo_frame: "new-payment-popup" } do %>

            MARK AS PAID
          <% end %>
        <% elsif current_user.designer? && designer.has_pending_payment? %>
          <%= link_to 'Request Payment Now', request_payment_designer_path(designer), class: 'request_btn', data: { 'turbo-method': :post } %>
        <% end %>
      </div>
    </div>

    <div class="designer_name finance">Payment History</div>

    <%= render 'payment_history', payments: payments, user: designer %>
  </div>
</div>

<turbo-frame id="new-payment-popup"></turbo-frame>

<!-- <script type="text/javascript">
  // document.querySelectorAll(".__range-step").forEach(function(ctrl) {
  //   var el = ctrl.querySelector('input');        
  //   var output = ctrl.querySelector('output'); 
  //   var newPoint, newPlace, offset;
  //   el.oninput =function(){ 
  //     // colorize step options
  //     ctrl.querySelectorAll("option").forEach(function(opt) {
  //       if(opt.value<=el.valueAsNumber)                
  //         opt.style.backgroundColor = '#00AB55';
  //       else
  //         opt.style.backgroundColor = '#00AB55';
  //     });           
  //     // colorize before and after
  //     var valPercent = (el.valueAsNumber  - parseInt(el.min)) / (parseInt(el.max) - parseInt(el.min));            
  //     var style = 'background-image: -webkit-gradient(linear, 0% 0%, 100% 0%, ' +
  //     'color-stop(' + valPercent + ', #00AB55), ' +
  //     'color-stop(' + valPercent + ', rgba(0, 171, 85, 0.48)));';
  //     el.style = style;

  //     // Popup
  //     if((' ' + ctrl.className + ' ').indexOf(' ' + '__range-step-popup' + ' ') > -1)
  //     {
  //       var selectedOpt=ctrl.querySelector('option[value="'+el.value+'"]');
  //       output.innerText= selectedOpt.text;
  //       output.style.left = "50%"; 
  //       output.style.left = ((selectedOpt.offsetLeft + selectedOpt.offsetWidth/2) - output.offsetWidth/2) + 'px'; 
  //     }           
  //   };
  //   el.oninput();
  // });

  // window.onresize = function(){
  //   document.querySelectorAll(".__range").forEach(function(ctrl) {
  //     var el = ctrl.querySelector('input');    
  //     el.oninput();    
  //   });
  // };
</script> -->

app/views/dashboard/_payment_history.html.erb
<div class="history_wrap">
  <div class="history_head">Payment History</div>
  <table class="history_table">
    <tr class="w-100">
      <th class="th">Date</th>
      <th class="th">Amount</th>
    </tr>

    <% payments.each do |payment| %>
      <tr>
        <td class="td"><%= payment.paid_at.strftime('%m/%d/%Y') %></td>
        <td class="td">$<%= format_number(payment.amount.to_f.round(2)) %></td>
      </tr>
    <% end %>
  </table>

  <%= render 'shared/pagination', records: payments, per_page: params[:per_page] %>

  <% if payments.present? %>
    <%= link_to export_payments_path(user_id: user.id, format: :csv), class: 'export_btn' do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="21" height="20" viewBox="0 0 21 20" fill="none">
        <path d="M3.8335 15.8333C3.8335 15.3731 4.20659 15 4.66683 15H16.3335C16.7937 15 17.1668 15.3731 17.1668 15.8333C17.1668 16.2936 16.7937 16.6667 16.3335 16.6667H4.66683C4.20659 16.6667 3.8335 16.2936 3.8335 15.8333Z" fill="white"/>
        <path d="M4.66683 16.6667C4.20659 16.6667 3.8335 16.2936 3.8335 15.8333V14.1667C3.8335 13.7064 4.20659 13.3333 4.66683 13.3333C5.12707 13.3333 5.50016 13.7064 5.50016 14.1667V15.8333C5.50016 16.2936 5.12707 16.6667 4.66683 16.6667Z" fill="white"/>
        <path d="M16.3335 16.6667C15.8733 16.6667 15.5002 16.2936 15.5002 15.8333V14.1667C15.5002 13.7064 15.8733 13.3333 16.3335 13.3333C16.7937 13.3333 17.1668 13.7064 17.1668 14.1667V15.8333C17.1668 16.2936 16.7937 16.6667 16.3335 16.6667Z" fill="white"/>
        <path d="M10.5002 12.5C10.3274 12.5013 10.1585 12.4489 10.0168 12.35L6.6835 10C6.30948 9.73468 6.22011 9.21704 6.4835 8.84167C6.61106 8.65963 6.80606 8.53609 7.02515 8.49854C7.24424 8.46098 7.46925 8.51251 7.65016 8.64167L10.5002 10.6333L13.3335 8.5C13.7017 8.22386 14.224 8.29848 14.5002 8.66667C14.7763 9.03486 14.7017 9.55719 14.3335 9.83333L11.0002 12.3333C10.8559 12.4415 10.6805 12.5 10.5002 12.5Z" fill="white"/>
        <path d="M10.5002 10.8333C10.0399 10.8333 9.66683 10.4602 9.66683 10V3.33333C9.66683 2.8731 10.0399 2.5 10.5002 2.5C10.9604 2.5 11.3335 2.8731 11.3335 3.33333V10C11.3335 10.4602 10.9604 10.8333 10.5002 10.8333Z" fill="white"/>
      </svg>
      Export
    <% end %>
  <% end %>
</div>

app/views/dashboard/_producer_dashboard.html.erb
<div class="hero_wrapper">
  <%= render "shared/sidebar" %>

  <div class="producer_panel_wrapper">
    <div class="order_head">
      <div class="head_content">
        <%= render 'shared/profile_head' %>
      </div>
    </div>

    <div class="designer_name"><%= producer.name %></div>

    <div class="total_wrapper">
      <div class="total_content">
        <div class="total_head">Total Earned</div>
        <div class="total_text">$<%= format_number(producer.total_earned) %></div>
      </div>

      <div class="total_content">
        <div class="total_head">Total Number of Orders Completed</div>
        <div class="total_text"><%= format_number(producer.no_of_completed_orders) %></div>
      </div>

      <div class="total_content">
        <div class="total_head">Total Number of Items Produced</div>
        <div class="total_text"><%= format_number(producer.no_of_item_produced) %></div>
      </div>
    </div>

    <div class="producer_payments">
      <div class="payment_head">Payments</div>

      <div class="payment_body">
        <div class="payment_items">
          <div class="items_head">Pending Payment</div>
          <div class="items_text">$<%= format_number(producer.pending_payment.to_f.round(2)) %></div>
        </div>

        <div class="payment_items">
          <div class="items_head">Received Payment</div>
          <div class="items_text green_text">$<%= format_number(producer.received_payment.to_f.round(2)) %></div>
        </div>

        <div class="payment_items">
          <div class="items_head">Total Amount</div>
          <div class="items_text blue_text">$<%= format_number((producer.pending_payment.to_f + producer.received_payment.to_f).round(2)) %></div>
        </div>
      </div>
    </div>

    <div class="next_payment_wrap">
      <div class="next_head">Requested Payment</div>
      <div class="next_content">
        <div class="content_head"><sup>$</sup><%= format_number(producer.requested_payment.to_f.round(2)) %></div>

        <!-- CURRENTLY NOT USABLE -->
        <!-- <fieldset class="formSlider">
          <div class="__range __range-step">
            <input value="3" type="range" max="5" min="1" step="0.01" list="ticks1">
            <datalist id="ticks1">
              <option value="1"></option>
              <option value="2"></option>
              <option value="3"></option>
              <option value="4"></option>
              <option value="5"></option>
            </datalist>
          </div>
        </fieldset> -->

        <% if current_user.admin? && producer.has_requested_payment? %>
          <div class="next_content_btn">
            <%= link_to new_payment_path(user_id: producer.id),
                class: 'request_btn',
                data: { turbo_frame: "new-payment-popup" } do %>

              MARK AS PAID
            <% end %>
          </div>
        <% elsif current_user.producer? && producer.has_pending_payment? %>
          <div class="next_content_btn">
            <%= link_to request_payment_producer_path(producer), data: { 'turbo-method': :post }, class: 'request_btn' do %>
              Request Payment Now
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <%= render 'payment_history', payments: payments, user: producer %>
  </div>
</div>

<turbo-frame id="new-payment-popup"></turbo-frame>

<!-- CURRENTLY NOT USABLE -->
<!-- <script type="text/javascript">
  // document.querySelectorAll(".__range-step").forEach(function(ctrl) {
  //   var el = ctrl.querySelector('input');        
  //   var output = ctrl.querySelector('output'); 
  //   var newPoint, newPlace, offset;
  //   el.oninput =function(){ 
  //     // colorize step options
  //     ctrl.querySelectorAll("option").forEach(function(opt) {
  //       if(opt.value<=el.valueAsNumber)                
  //         opt.style.backgroundColor = '#00AB55';
  //       else
  //         opt.style.backgroundColor = '#00AB55';
  //     });           
  //     // colorize before and after
  //     var valPercent = (el.valueAsNumber  - parseInt(el.min)) / (parseInt(el.max) - parseInt(el.min));            
  //     var style = 'background-image: -webkit-gradient(linear, 0% 0%, 100% 0%, ' +
  //     'color-stop(' + valPercent + ', #00AB55), ' +
  //     'color-stop(' + valPercent + ', rgba(0, 171, 85, 0.48)));';
  //     el.style = style;

  //     // Popup
  //     if((' ' + ctrl.className + ' ').indexOf(' ' + '__range-step-popup' + ' ') > -1)
  //       {
  //         var selectedOpt=ctrl.querySelector('option[value="'+el.value+'"]');
  //         output.innerText= selectedOpt.text;
  //         output.style.left = "50%"; 
  //         output.style.left = ((selectedOpt.offsetLeft + selectedOpt.offsetWidth/2) - output.offsetWidth/2) + 'px'; 
  //       }           
  //   };
  //   el.oninput();
  // });

  // window.onresize = function(){
  //   document.querySelectorAll(".__range").forEach(function(ctrl) {
  //     var el = ctrl.querySelector('input');    
  //     el.oninput();    
  //   });
  // };
</script> -->

app/views/dashboard/index.html.erb
<% if current_user.producer? %>
  <%= render "producer_dashboard", producer: @user, payments: @payments %>
<% elsif current_user.designer? %>
  <%= render "designer_dashboard", designer: @user, payments: @payments %>
<% else %>
  <div class="hero_wrapper">
    <%= render "shared/sidebar" %>
    <div class="producer_panel_wrapper">

      <div class="order_head">
        <div class="head_content">
          <%= render 'shared/profile_head' %>
        </div>
      </div>

      <div class="producer_payments">
        <div class="payment_head">Payments</div>
        <div class="payment_body">
          <% @producers.each do |producer| %>
            <div class="payment_items">
              <div class="td"> <%= link_to producer.name, producer_dashboard_path(producer_id: producer.id) %></div>
            </div>
          <% end %>

          <% @designers.each do |designer| %>
            <div class="payment_items">
              <div class="td"> <%= link_to designer.name, designer_dashboard_path(designer_id: designer.id) %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/dashboard/show.html.erb
<% if @designer.present? %>
	<%= render "designer_dashboard", designer: @designer, payments: @payments %>
<% elsif @producer.present? %>
	<%= render "producer_dashboard", producer: @producer, payments: @payments %>
<% end %>