config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"

  get '/dashboard/producer/:producer_id', to: 'dashboard#show', as: :producer_dashboard
  get '/dashboard/designer/:designer_id', to: 'dashboard#show', as: :designer_dashboard

  get 'dashboard/payment_amount_popup'

  get '/states', to: 'addresses#get_states'
  post '/close_modal/:modal_id', to: 'modals#close', as: :close_modal

  resources :products, only: [:index, :show, :new, :create,:edit, :update] do
    delete 'remove_variant', on: :member
    get 'edit_producer', on: :member
    patch 'update_producer', on: :member
  end

  resources :orders do
    member do
      get :download
      get :confirm
      get :reject
      get :send_message
      post :message_create
      get :cancel_request
      post :update_cancel_status
      get :select_variant
      get :assignee
      post :assignee_create
      get :assignee_remove_confirmation
      delete :assigne_remove
      get :on_hold_popup
      get :in_production_popup
      get :rejected_popup
      get :fullfilled_popup
      get :delete_confirmation
      get :cancel_order
      get :new_cancel_request
      post :create_cancel_request
      get :update_priority
      get :request_revision
      patch :request_revision_update
      post :create_address
      post :order_update_shipping
      delete :remove_product
      delete :remove_product_image
      delete :remove_design_files
      get :set_dimensions
      post :update_dimensions
      get :update_job_price
      patch :assigne_update_price
      get :order_slip
      get :duplicate_order
      get :edit_sender
      post :update_sender
      delete :remove_shipo_lable
      get :download_shippo_label
      post :undo
      get :save_changes_confirmation
    end

    collection do
      get :add_new_product
      get :select_variant
      get :all_producer
      get :cancel_order_index
      get :new_order_product
      post :etsy_import
    end
  end

  resources :variants do
    get :inventory, on: :collection
    get :producer_inventory, on: :member
  end

  resources :producers_variants, only: [:edit, :update] do
    member do
      get :edit_inventory
      patch :update_inventory
    end
  end

  resources :producers, only: [:edit, :update] do
    post :request_payment, on: :member
    resources :producer_variant_histories, only: [:index]
  end

  resources :designers, only: [] do
    post :request_payment, on: :member
  end

  # Sessions routes
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/etsy/authorize', to: 'etsy#authorize'
  get '/etsy/callback', to: 'etsy#callback'

  resources :payments, only: [:new, :create] do
    get :export, on: :collection
  end

  namespace :admin do
    resources :orders, only: [:index] do
      collection do
        get :on_hold
        get :rejected
        get :in_production
        get :fulfilled
      end
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
  before_action :set_per_page

  def index
    @orders = Order.search(params).order(created_at: :desc).paginate(page: params[:page], per_page: @per_page)

    render_result
  end

  def on_hold

  end

  def rejected

  end

  def in_production

  end

  def fulfilled

  end

  private

  def set_per_page
    @per_page = params[:per_page] || Rails.configuration.settings.default_per_page
  end

  def render_result
    respond_to do |format|
      format.html
      format.js do
        html_data = render_to_string(partial: "orders/orders_table", locals: { orders: @orders }, layout: false)

        render json: { html_data: html_data }
      end
    end
  end
end

app/controllers/designer/orders_controller.rb
class Designer::OrdersController < ApplicationController

end

app/controllers/orders_controller.rb
require 'open-uri'

class OrdersController < ApplicationController
  before_action :initialize_shippo
  before_action :find_order, only: [:send_message,
                                    :update_cancel_status,
                                    :message_create,
                                    :update,
                                    :edit,
                                    :destroy,
                                    :assignee,
                                    :assignee_create,
                                    :on_hold_popup,
                                    :in_production_popup,
                                    :rejected_popup,
                                    :fullfilled_popup,
                                    :assignee_remove_confirmation,
                                    :create_cancel_request,
                                    :new_cancel_request,
                                    :update_priority,
                                    :request_revision,
                                    :request_revision_update,
                                    :create_address,
                                    :order_update_shipping,
                                    :remove_product,
                                    :remove_product_image,
                                    :remove_design_files,
                                    :set_dimensions,
                                    :update_dimensions,
                                    :update_job_price,
                                    :order_slip,
                                    :duplicate_order,
                                    :edit_sender,
                                    :update_sender,
                                    :remove_shipo_lable,
                                    :download_shippo_label,
                                    :save_changes_confirmation,
                                    :undo]

  before_action :set_common_data, only: [:on_hold_popup, :in_production_popup, :rejected_popup, :fullfilled_popup]

  def etsy_import
    if params[:receipt_id].present?
      if EtsyService.import_order(receipt_id: params[:receipt_id], access_token: current_user.etsy_access_token)
        redirect_to orders_path
      end
    end
  end

  def index
    per_page  = params[:per_page] || Rails.configuration.settings.default_per_page
    @orders   = Order.search(params).paginate(page: params[:page], per_page: per_page)
    @products = Product.all

    if current_user.type.eql?('Producer')
      @orders = @orders
                     .where(order_products: { user_id: current_user.id })
                     .where.not(order_status: ["cancel", "onhold", "rejected"])

    elsif current_user.type.eql?('Designer')
      @orders =  @orders
                      .joins(:assign_details)
                      .where.not(assign_details: nil)
                      .order(created_at: :desc)
    else
      @orders = @orders.order(created_at: :desc)
    end

    respond_to do |format|
      format.html
      format.js do
        if current_user.type.eql?('Admin')
          html_data = render_to_string(partial: "orders/orders_table", locals: { orders: @orders }, layout: false)
        elsif current_user.type.eql?('Designer')
          html_data = render_to_string(partial: "orders/designer_orders_table", locals: { orders: @orders }, layout: false)
        elsif current_user.type.eql?('Producer')
          html_data = render_to_string(partial: "orders/producer_all_order", locals: { orders: @orders }, layout: false)
        end

        render json: { html_data: html_data }
      end
    end
  end

  def save_changes_confirmation; end

  def new
    @order = Order.create(order_status: :onhold, order_edit_status: :incomplete)
    redirect_to edit_order_path(@order)
  end

  def edit
    @order     = Order.find_by(id: params[:id])
    @producers = Producer.all
    @error_message = params[:error_message]

    if @order.shippo_shipment_id.present?
      begin
        shipment = Shippo::Shipment.get(@order.shippo_shipment_id)
      rescue
        shipment = {}
      end

      @rates = shipment['rates']
    end
  end

  def update
    if params[:request_type] == "Confirm"
      @order.update(order_edit_status: 1, order_status: 3, mark_completed_by_producer: true)
      @order.update_producer_payments
    elsif params[:request_type] == "Reject"
      @order.update(order_status: 1, reject_reason: params[:order][:reject_reason])
      @order.decrease_producer_payments
    elsif params[:request_type] == "Cancel"
      @order.update(order_status: 4)
    else
      @order.update(additional_comment: params[:additional_comment])

      if @order.incomplete? && params[:submit_type].eql?('mark_complete')
        @order.update(order_edit_status: :completed, request_revision: false)
        @order.update_designer_payments
      end

      if params[:shipping_label_image].present?
        @order.shipping_label_image.attach(params[:shipping_label_image])

        if params[:submit_type].eql?('design_added') && !@order.temp_shipping_label_image.attached?
          @order.update(shipping_label_image_is_temporary: true)
        end
      end

      if params[:packing_slip_image].present?
        @order.packing_slip_image.attach(params[:packing_slip_image])

        if params[:submit_type].eql?('design_added') && !@order.temp_packing_slip_image.attached?
          @order.update(packing_slip_image_is_temporary: true)
        end
      end

      if params[:gift_message_slip_image].present?
        @order.gift_message_slip_image.attach(params[:gift_message_slip_image])

        if params[:submit_type].eql?('design_added') && !@order.temp_gift_message_slip_image.attached?
          @order.update(gift_message_slip_image_is_temporary: true)
        end
      end

      if params[:design_file_1_image].present?
        @order.design_file_1_image.attach(params[:design_file_1_image])

        if params[:submit_type].eql?('design_added') && !@order.temp_design_file_1_image.attached?
          @order.update(design_file_1_image_is_temporary: true)
        end
      end

      if params[:design_file_2_image].present?
        @order.design_file_2_image.attach(params[:design_file_2_image])

        if params[:submit_type].eql?('design_added') && !@order.temp_design_file_2_image.attached?
          @order.update(design_file_2_image_is_temporary: true)
        end
      end

      if params[:additional_file_image].present?
        @order.additional_file_image.attach(params[:additional_file_image])

        if params[:submit_type].eql?('design_added') && !@order.temp_additional_file_image.attached?
          @order.update(additional_file_image_is_temporary: true)
        end
      end

      if params[:producers_variants].present?
        params[:producers_variants].each do |order_product_id, quantity|
          order_product = @order.order_products.find_by(id: order_product_id)
          order_product.update(product_quantity: quantity.to_i)

          if params[:front_side_image].present? && params[:front_side_image][order_product_id].present?
            order_product.front_side_image.attach(io: params[:front_side_image][order_product_id], filename: "design-file-#{order_product.id}")
            
            if params[:submit_type].eql?('design_added') && !order_product.temp_front_side_image.present?
              order_product.update(front_image_is_temporary: true)
            end
          end

          if params[:back_side_image].present? && params[:back_side_image][order_product_id].present?
            order_product.back_side_image.attach(io: params[:back_side_image][order_product_id], filename: "design-file-#{order_product.id}")
          
            if params[:submit_type].eql?('design_added') && !order_product.temp_back_side_image.present?
              order_product.update(back_image_is_temporary: true)
            end
          end
        end
      end

      unless params[:submit_type].eql?('design_added')
        @order.order_products.temporary_removed.destroy_all
        @order.order_products.temporary_added.update_all(temporary_added: false)

        @order.temp_shipping_label_image.purge if @order.temp_shipping_label_image.attached?
        @order.temp_packing_slip_image.purge if @order.temp_packing_slip_image.attached?
        @order.temp_gift_message_slip_image.purge if @order.temp_gift_message_slip_image.attached?
        @order.temp_design_file_1_image.purge if @order.temp_design_file_1_image.attached?
        @order.temp_design_file_2_image.purge if @order.temp_design_file_2_image.attached?
        @order.temp_additional_file_image.purge if @order.temp_additional_file_image.attached?

        @order.update(
          shipping_label_image_is_temporary: false,
          packing_slip_image_is_temporary: false,
          gift_message_slip_image_is_temporary: false,
          design_file_1_image_is_temporary: false,
          design_file_2_image_is_temporary: false,
          additional_file_image_is_temporary: false
        )

        @order.order_products.each do |order_product|
          order_product.temp_front_side_image.purge if order_product.temp_front_side_image.attached?
          order_product.temp_back_side_image.purge if order_product.temp_back_side_image.attached?

          order_product.update(front_image_is_temporary: false, back_image_is_temporary: false)
        end
      end
    end

    @order.update_pricing

    respond_to do |format|
      format.turbo_stream do
        if params[:submit_type].eql?('shipping')
          render turbo_stream: turbo_stream.replace("order-form-content", partial: 'orders/step_two', locals: { order: @order })
        elsif params[:submit_type].eql?('design_added')
          render turbo_stream: turbo_stream.replace("order-form-content", partial: 'orders/edit_step_one', locals: { order: @order })
        else
          redirect_to orders_path
        end
      end

app/controllers/producer/orders_controller.rb
class Producer::OrdersController < ApplicationController

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_admin_all_order.html.erb
<div class="orders_details_box">
  <div class="order_details_data">
    <div class="order_table_section">
      <div class="order_info_table designer_info_table">
        <div class="thead">
          <div class="thead_row">
            <div class="order_th first">&nbsp;</div>
            <div class="order_th second">Order ID</div>
            <div class="order_th three">Etsy/Amazon Order ID</div>
            <div class="order_th four">Customer Name</div>
            <div class="order_th five">Total Items</div>
            <div class="order_th six">Price</div>
            <div class="order_th seven">Order Status</div>
            <div class="order_th eight">Assignee</div>
            <div class="order_th nine">Order Date</div>
            <div class="order_th ten">Order by</div>
            <div class="order_th last">More Actions</div>
          </div>
        </div>
        <div class="tbody">
          <% orders.each do |order| %>
            <div class="tbody_row">
              <!-- Checkbox -->
              <div class="order_td td_icon first">
                <div class="custom_checkbox_wrapper">
                  <input type="checkbox" name="" id="<%= order.id %>" class="check_field">
                  <label for="<%= order.id %>"></label>
                </div>
              </div>
              <!-- Checkbox /-->

              <!-- Order ID -->
              <div class="order_td second">
                <div class="order_id_icon">
                  <span class="order_num"><%= order.id %></span>
                </div>
              </div>
              <!-- Order ID /-->

              <!-- Etsy/Amazon Order ID -->
              <div class="order_td three"><%= order.etsy_order_id %></div>
              <!-- Etsy/Amazon Order ID /-->

              <!-- Customer Name -->
              <% if order.address.present?%>
                <div class="order_td four"><%= order.address.fullname %></div>
              <%else%>
                <div class="order_td four">-</div>
              <%end%>
              <!-- Customer Name /-->

              <!-- Total Items -->
              <% if order.order_products.pluck(:product_quantity).present? %>
                <div class="order_td five"><%= order.order_products.pluck(:product_quantity).compact.sum %></div>
              <% else%>
                <div class="order_td five">-</div>
              <%end%>
              <!-- Total Items /-->

              <!-- Price -->
              <div class="order_td six">$<%= order.price %></div>
              <!-- Price /-->

              <!-- Order Status -->
              <div class="order_td seven">
                <div class="order_status_icon">
                  <% if order.order_status == "inproduction" %>
                    <div class="in_production custom_badge">
                      In Production
                    </div>
                  <% elsif order.order_status == "onhold" %>
                    <div class="custom_badge">
                      On Hold
                    </div>
                  <% elsif order.order_status == "rejected" %>
                    <div class="rejectd custom_badge">
                      Rejected 
                    </div>
                  <% elsif order.order_status == "fullfilled" %>
                    <div class="fulfiled custom_badge">
                      Fullfilled
                    </div>
                  <% else %>
                    <div class="rejectd custom_badge">
                      Cancel
                    </div>
                  <% end %>
                </div>
              </div>
              <!-- Order Status /-->

              <!-- Assignee -->
              <div class="order_td eight">
                <div class="order_priority_icon">
                  <% if order.assign_details.present? %>
                    <div class="icon_with_name <%= order.order_edit_status.eql?("completed") ? 'completed' : 'pending' %>">
                      <span class="assign_name"><%= order.assignee_name %></span>
                      <% if order.assign_details.last.price_for_total.present? || order.assign_details.last.price_per_design.present? %>
                        <span class="price">
                          $<%= order.assign_details.last.price_for_total.presence || order.assign_details.last.price_per_design.to_f * order.order_products.pluck(:product_quantity).compact.sum.to_i %>
                        </span>
                      <% end %>
                      <% if order.order_edit_status.eql?("completed") %>
                        <%= image_tag "complete", alt: "icon", class: "complete_icon" %>
                      <% else %>
                        <%= image_tag 'incomplete.png', alt: 'icon'%>
                      <% end %>
                    </div>
                    <% unless order.assign_details.last.price_for_total.present? || order.assign_details.last.price_per_design.present? %>
                      <span class="no_price">Not Priced</span>
                    <% end %>
                  <% else %>
                    <div class="icon_with_name not_assign">
                      <%= link_to 'Assignee', assignee_order_path(order), data: { turbo_frame: "assigne-order-modal" } %>
                      <%= image_tag "ic_user_group", alt: "icon", class: "complete_icon" %>
                    </div>
                  <% end %>
                </div>
              </div>
              <!-- Assignee / -->

              <!-- Order Date -->
              <div class="order_td nine"><%= order.created_at.strftime('%m/%d/%y') %></div>
              <!-- Order Date / -->

              <!-- Order by -->
              <div class="order_td ten">
                Amazon
              </div>
              <!-- Order by / -->

              <!-- More Actions -->
              <div class="order_td last">
                <div class="more_menu">
                  <% if order.order_status == "onhold" %>
                    <a href="<%= on_hold_popup_order_path(order) %>" data-turbo-frame="on-hold-order-modal" class= "more_link">
                      <%= image_tag 'View.png', alt: 'icon'%>
                    </a>
                  <% elsif order.order_status == "rejected" %>
                    <a href="<%= rejected_popup_order_path(order) %>" data-turbo-frame="rejected-order-modal" class= "more_link">
                      <%= image_tag 'View.png', alt: 'icon'%>
                    </a>
                  <% elsif order.order_status == "fullfilled" %>
                    <a href="<%= fullfilled_popup_order_path(order) %>" data-turbo-frame="fullfilled-order-modal" class= "more_link">
                      <%= image_tag 'View.png', alt: 'icon'%>
                    </a>
                  <% else %>
                    <a href="<%= in_production_popup_order_path(order) %>" data-turbo-frame="in-production-order-modal" class= "more_link">
                      <%= image_tag 'View.png', alt: 'icon'%>
                    </a>
                  <% end %>

                  <% if order.order_status == "rejected" || order.order_status == "onhold" || order.order_status == "cancel" %>
                    <%= link_to edit_order_path(order), class: 'more_link' do %>
                      <%= image_tag 'edit_row.png', alt: 'icon' %>
                    <% end %>

                    <% if order.order_status == "rejected" %>
                      <a href="<%= cancel_order_order_path(order) %>"  data-turbo-frame="cancel-order-modal" class= "more_link">
                        <%= image_tag 'close.png', alt: 'icon' %>
                      </a>
                    <% else %>
                      <a href="<%= delete_confirmation_order_path(order) %>"  data-turbo-frame="destroy-order-modal" class= "more_link">
                        <%= image_tag 'delete.png', alt: 'icon' %>
                      </a>
                    <% end %>
                  <% end %>

                  <div class="more_link">
                    <span>&nbsp;</span>
                  </div>

                  <div class="drop_menu">
                    <div class="drop_icon_box">
                      <%= image_tag 'ic_more.png', alt: 'icon', class: 'more_icon' %>
                    </div>

                    <div class="menu_drop">
                      <div class="status_wrapper_pop">
                        <% if order.order_status == "onhold"%>
                          <a href="<%= order_slip_order_path(order, format: :pdf) %>" class="status_content">
                            <%= image_tag "download", alt:"icon", class:"icon" %>
                            <div class="content_text">Download ETSY Packing Slip</div>
                          </a>
                          <% unless order.assign_details.present? %>
                            <a href="<%= assignee_order_path(order)%>" data-turbo-frame="assigne-order-modal" class="status_content">
                              <%= image_tag "ic_user_group", alt:"icon", class:"icon" %>
                              <div class="content_text">Assign Order</div>
                            </a>
                          <% else %>
                            <a href="<%= assignee_remove_confirmation_order_path(order)%>" data-turbo-frame="assignee-remove-order-modal" class="status_content">
                              <%= image_tag "orange_user", alt:"icon", class:"icon" %>
                              <div class="content_text">Remove Assignee from the Order</div>
                            </a>
                            <a href="<%= update_job_price_order_path(order)%>" data-turbo-frame="update-job-price-order-modal" class="status_content">
                              <%#= image_tag "ic_user_group", alt:"icon", class:"icon" %>
                              <div class="icon">$</div>
                              <div class="content_text">Update the job price for the assignee.</div>
                            </a>
                            <a href= "<%= request_revision_order_path(order)%>" data-turbo-frame="request-revision-order-modal" class="status_content">
                              <%= image_tag "info_outline", alt:"icon", class:"icon" %>
                              <div class="content_text">Request Revision from Assignee</div>
                            </a>
                          <% end %>
                        <% elsif order.order_status == "inproduction"%>
                          <div class="status_wrapper_pop">
                            <a href="<%=new_cancel_request_order_path(order)%>" data-turbo-frame="cancel-request-order-modal" class="status_content">
                              <%= image_tag "call", alt:"icon", class:"icon" %>
                              <div class="content_text orange_text">Request Cancellation</div>
                            </a>
                            <a href="<%= update_priority_order_path(order)%>" class="status_content">
                              <%= image_tag "flash", alt:"icon", class:"icon" %>
                              <div class="content_text">Mark Order as Urgent</div>
                            </a>
                            <%= link_to send_message_order_path(order), class: 'status_content', data: {turbo_frame: "send-message-order-modal"} do %>
                              <%= image_tag "ic_chat", alt:"icon", class:"icon" %>
                              <div class="content_text">Add Additional Comment</div>
                            <%end%>
                          </div>
                        <% elsif order.order_status == "rejected"%>
                          <div class="edit_list_pop">
                            <%= link_to order_slip_order_path(order, format: :pdf), class: 'edit_box' do %>
                              <%= image_tag "download", alt:"icon", class:"icon" %>
                              <div class="edit_text">Print ETSY Packing Slip</div>
                            <% end %>

                            <div class="edit_box">
                              <a href="<%= request_revision_order_path(order)%>" data-turbo-frame="request-revision-order-modal" class="status_content">
                                <%= image_tag "info_outline", alt:"icon", class:"icon" %>
                                <div class="edit_text">Request Revision</div>
                              </a>
                            </div>

                            <div class="edit_box">
                              <a href="<%= assignee_remove_confirmation_order_path(order)%>" data-turbo-frame="assignee-remove-order-modal" class="status_content">
                                <%= image_tag "orange_user", alt:"icon", class:"icon" %>
                                <div class="edit_text">Remove Assignee from the Order</div>
                              </a>
                            </div>
                          </div>
                        <% end %>
                        <a href="<%= duplicate_order_order_path(order)%>" class="status_content">
                          <%= image_tag "bxs_copy", alt:"icon", class:"icon" %>
                          <div class="content_text">Duplicate Order
                            <div class="sub_text">Creates a new manual order</div>
                          </div>
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- More Actions / -->
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="table_footer_wrap">
    <div class="content_btn">
      <div class="center"><input type="checkbox" /></div>

      <div class="content_text">Dense</div>
    </div>

    <%= render 'shared/pagination', records: orders, per_page: params[:per_page] %>
  </div>
</div>

app/views/orders/_error_message.html.erb
<div id="order-error-message">
  <% if error_message.present? %>
    <div class="text-center w-full text-danger"><%= error_message %></div>
  <% end %>
</div>

app/views/orders/edit.html.erb
<div class="hero_wrapper">
  <div class="manual_order_wrapper">
    <div class="manual_order_header">
      <%= link_to save_changes_confirmation_order_path(@order), class: "back_btn_wrap", data: { turbo_frame: "save-changes-order-model" } do %>
        <%= image_tag 'start_icon.png', alt: 'icon', class: 'back_icon' %>
        <span>Back to My Orders</span>
      <% end %>
      <div class="header_text">Order ID <%= @order.id %></div>
    </div>

    <div class="manual_content_wrap">
      <div class="new_product_section">
        <div class="form_step">
          <span id="order-form-step-one" class="step choose_products">1</span>
          <span id="order-form-step-two" class="step shipping">2</span>
          <span id="order-form-step-three" class="step submit_offers">3</span>
        </div>

        <%= link_to add_new_product_orders_path(order_id: @order.id), class: "new_product_btn", id: 'add-new-product-link', data: { turbo_frame: "add-new-product-order-modal" } do %>
          <%= image_tag 'shopping_cart.png', alt: 'icon', class: 'cart_icon' %>
          <span class="new_text">Add New Products</span>
        <% end %>
      </div>

      <% if current_user.designer? && @order.assign_details&.last.present? %>
        <% assign_detail = @order.assign_details.last %>
        <% if assign_detail.additional_comment.present? %>
          <div class="important-note px-4">
            <%= image_tag 'ic_alert' %>
            Note: <%= assign_detail.additional_comment %>
          </div>
        <% end %>

        <% if @order.request_revision? && @order.revision_info.present? %>
          <div class="important-note mt-2 px-4">
            <%= image_tag 'ic_alert' %>
            Revision Request: <%= @order.revision_info %>
          </div>
        <% end %>
      <% end %>

      <turbo-frame id="save-changes-order-model"></turbo-frame>
      <turbo-frame id="all-producer-order-modal"></turbo-frame>
      <turbo-frame id="add-new-product-order-modal"></turbo-frame>
      <turbo-frame id="order-success-popup-modal"></turbo-frame>
      <turbo-frame id="set-dimensions"></turbo-frame>
      <turbo-frame id="edit-sender"></turbo-frame>
      <turbo-frame id="request-revision-order-modal"></turbo-frame>

      <%= render 'orders/error_message', error_message: @error_message %>

      <% if params[:step].present? && params[:step].eql?('shipping_method') && @order.shippo_shipment_id.present? %>
        <%= render 'step_three', order: @order, rates: @rates, address: @order.address, sender: @order.sender %>
      <% elsif params[:step].present? && params[:step].eql?('customer') %>
        <%= render 'step_two', order: @order %>
      <% else %>
        <%= render 'edit_step_one', order: @order %>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('.toggle_icon').click(function() {
    $(this).toggleClass('rotate_icon');
    $(this).closest('.product_list_section').find('.collapse_data').slideToggle();
  });

  $('.delete_img').click(function() {
    $(this).closest('.content_img').find('.avatar-edit').css('display', 'flex').find('.upload_field').val('');
    $(this).closest('.content_img').find('.avatar-preview').hide();
    $(this).closest('.content_img').find('.delete_img').hide();
  });
</script>

<style type="text/css">
  input.invalid {
    background-color: #ffdddd;
  }
</style>