config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"

  get '/dashboard/producer/:producer_id', to: 'dashboard#show', as: :producer_dashboard
  get '/dashboard/designer/:designer_id', to: 'dashboard#show', as: :designer_dashboard

  get 'dashboard/payment_amount_popup'

  get '/states', to: 'addresses#get_states'
  post '/close_modal/:modal_id', to: 'modals#close', as: :close_modal

  resources :products, only: [:index, :show, :new, :create,:edit, :update] do
    delete 'remove_variant', on: :member
    get 'edit_producer', on: :member
    patch 'update_producer', on: :member
  end

  resources :orders do
    member do
      get :download
      get :confirm
      get :reject
      get :send_message
      post :message_create
      get :cancel_request
      post :update_cancel_status
      get :select_variant
      get :assignee
      post :assignee_create
      get :assignee_remove_confirmation
      delete :assigne_remove
      get :on_hold_popup
      get :in_production_popup
      get :rejected_popup
      get :fullfilled_popup
      get :delete_confirmation
      get :cancel_order
      get :new_cancel_request
      post :create_cancel_request
      get :update_priority
      get :request_revision
      patch :request_revision_update
      post :create_address
      post :order_update_shipping
      delete :remove_product
      delete :remove_product_image
      delete :remove_design_files
      get :set_dimensions
      post :update_dimensions
      get :update_job_price
      patch :assigne_update_price
      get :order_slip
      get :duplicate_order
      get :edit_sender
      post :update_sender
      delete :remove_shipo_lable
      get :download_shippo_label
      post :undo
      get :save_changes_confirmation
    end

    collection do
      get :add_new_product
      get :select_variant
      get :all_producer
      get :cancel_order_index
      get :new_order_product
      post :etsy_import
    end
  end

  resources :variants do
    get :inventory, on: :collection
    get :producer_inventory, on: :member
  end

  resources :producers_variants, only: [:edit, :update] do
    member do
      get :edit_inventory
      patch :update_inventory
    end
  end

  resources :producers, only: [:edit, :update] do
    post :request_payment, on: :member
    resources :producer_variant_histories, only: [:index]
  end

  resources :designers, only: [] do
    post :request_payment, on: :member
  end

  # Sessions routes
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/etsy/authorize', to: 'etsy#authorize'
  get '/etsy/callback', to: 'etsy#callback'

  resources :payments, only: [:new, :create] do
    get :export, on: :collection
  end

  namespace :admin do
    resources :orders, only: [:index] do
      collection do
        get :on_hold
        get :rejected
        get :in_production
        get :fulfilled
      end
    end
  end
end

app/models/producers_variant.rb
# == Schema Information
#
# Table name: producers_variants
#
#  id         :bigint           not null, primary key
#  user_id    :bigint
#  variant_id :bigint
#  inventory  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  aisle_no   :string
#
class ProducersVariant < ApplicationRecord
  has_paper_trail

  # Associations
  belongs_to :producer, foreign_key: :user_id, class_name: "Producer"
  belongs_to :variant

  has_many :producer_variant_histories, dependent: :destroy

  def self.search(params)
    results = all.joins(variant: :product)

    if params[:query].present?
      results = results.where('LOWER(variants.real_variant_sku) LIKE :query
                               OR LOWER(variants.color) LIKE :query
                               OR CAST(variants.product_id AS TEXT) LIKE :query
                               OR LOWER(products.name) LIKE :query', query: "%#{params[:query].downcase}%")
    end

    results.order(created_at: :desc)
  end

  def inventory_for_admin
    used_quantity = OrderProduct
                      .joins(:order)
                      .where(orders: { order_status: [:onhold, :inproduction, :fullfilled] })
                      .or(OrderProduct.joins(:order).where(orders: { mark_completed_by_producer: true }))
                      .where(variant_id: variant_id, user_id: user_id)
                      .sum(:product_quantity)

    available_quantity = inventory.to_i - used_quantity.to_i
    available_quantity = 0 if available_quantity < 0
    available_quantity
  end

  def inventory_for_producer
    used_quantity = OrderProduct.joins(:order).where(order: { mark_completed_by_producer: :true }, variant_id: variant_id, user_id: user_id).sum(:product_quantity)
    available_quantity = inventory.to_i - used_quantity.to_i
    available_quantity = 0 if available_quantity < 0
    available_quantity
  end

  def inventory_for_user(user)
    user.producer? ? inventory_for_producer : inventory_for_admin
  end
end

app/controllers/producers_variants_controller.rb
class ProducersVariantsController < ApplicationController
  before_action :find_producer_variant, only: [:edit, :update, :edit_inventory, :update_inventory]

  def edit
    @variant = @producer_variant.variant
  end

  def update
    @producer_variant.update(producer_variant_params)

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("producer-inventory-row-#{@producer_variant.id}", partial: 'variants/producer_inventory_row', locals: { producer_variant: @producer_variant }),
          turbo_stream.replace("edit-aisle-modal", partial: 'shared/close_modal', locals: { modal_id: 'edit-aisle-modal' })
        ]
      end
    end
  end

  def edit_inventory
    @variant = @producer_variant.variant
  end

  def update_inventory
    inventory = @producer_variant.inventory

    producer_variant_history = @producer_variant.producer_variant_histories.create(
      prev_inventory: inventory,
      tracking_no:    params[:tracking_no],
      invoice_no:     params[:invoice_no],
      user:           current_user
    )

    if params[:increased_inventory].present? && params[:increased_inventory].to_i > 0
      inventory += params[:increased_inventory].to_i

      producer_variant_history.update(new_inventory: inventory, reason: params[:reason_for_increase])
    elsif params[:decreased_inventory].present? && params[:decreased_inventory].to_i > 0
      inventory -= params[:decreased_inventory].to_i

      producer_variant_history.update(new_inventory: inventory, reason: params[:reason_for_decrease])
    else
      producer_variant_history.destroy
    end

    @producer_variant.update(inventory: inventory)

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("producer-inventory-row-#{@producer_variant.id}", partial: 'variants/producer_inventory_row', locals: { producer_variant: @producer_variant }),
          turbo_stream.replace("edit-inventory-modal", partial: 'shared/close_modal', locals: { modal_id: 'edit-inventory-modal' })
        ]
      end
    end
  end

  private

  def find_producer_variant
    @producer_variant = ProducersVariant.find(params[:id])
  end

  def producer_variant_params
    params.require(:producers_variant).permit(:aisle_no)
  end
end

app/views/producers_variants/edit.html.erb
<turbo-frame id="edit-aisle-modal">
  <div class="edit_aisle_pop_model">
    <div class="edit_aisle_pop_wrapper">
      <div id="edit_aisle_pop"
           class="edit_pop_wrap small_pop update_assign_pop edit_aisle_pop"
           data-controller="modals aisle"
           data-modals-modal-id-value="edit-aisle-modal">

        <%= form_for @producer_variant, url: producers_variant_path(@producer_variant) do |f| %>
          <%= image_tag "close", alt: "close", class: "close_icon" %>

          <div class="edit_head mb-0">Edit Aisle: <%= @variant.real_variant_sku %></div>
          <div class="current_qty">Current Aisle: <%= @producer_variant.aisle_no %></div>

          <%= f.text_field :aisle_no, class: 'edit_aisle_input', placeholder: 'Enter New Aisle No', data: { 'aisle-target': 'aisleInput' } %>

          <div class="current_qty">New Aisle: <span id="new-aisle-text" data-aisle-target="newAisleText"></span></div>
          <%= f.submit 'Submit', class: 'inventory_edit_btn' %>
        <% end %>
      </div>
    </div>  
  </div>
</turbo-frame>

app/views/producers_variants/edit_inventory.html.erb
<turbo-frame id="edit-inventory-modal">
  <div id="edit_invntry_qty_popup"
       class="edit_invntry_qty_popup show_popup"
       data-controller="modals edit-inventory"
       data-modals-modal-id-value="edit-inventory-modal"
       data-edit-inventory-current-quantity-value="<%= @producer_variant.inventory_for_user(current_user) %>">

    <div class="popup_wrapper">
      <%= form_tag update_inventory_producers_variant_path(@producer_variant), method: :patch do %>
        <div class="edit_pop_wrap">
          <%= image_tag 'close.png', alt: 'icon', class: 'cross_icon cancel_qty' %>

          <div class="edit_head">Edit Inventory QTY: <%= @variant.real_variant_sku %></div>
          <div class="current_qty">Current Quantity: <span id="current_qty"><%= @producer_variant.inventory_for_user(current_user) %></span></div>
          <button type="button" class="current_qty green_box d-block w-100" id="increase_qty" data-edit-inventory-target="increaseButton">INCREASE QTY</button>

          <div class="increase_box" data-edit-inventory-target="increaseBox">
            <div class="input_group">
              <%= label_tag :increased_inventory, 'Add Quantity' %>
              <%= number_field_tag :increased_inventory, 0, class: "item_text", data: { 'edit-inventory-target': 'quantityPlus' }, min: 0 %>
            </div>

            <div class="input_group">
              <%= label_tag :reason_for_increase, 'Reason for Increase' %>
              <%= text_field_tag :reason_for_increase, '', data: { 'edit-inventory-target': 'increaseReason' } %>
            </div>

            <div class="input_group">
              <%= label_tag :tracking_no, 'Tracking No' %>
              <%= text_field_tag :tracking_no, '', data: { 'edit-inventory-target': 'trackingNo' } %>
            </div>

            <div class="input_group">
              <%= label_tag :invoice_no, 'Invoice No' %>
              <%= text_field_tag :invoice_no, '', data: { 'edit-inventory-target': 'invoiceNo' } %>
            </div>
          </div>

          <button type="button" class="current_qty orange_box d-block w-100" id="decrease_qty" data-edit-inventory-target="decreaseButton">DECREASE QTY</button>

          <div class="decrease_box" data-edit-inventory-target="decreaseBox">
            <div class="input_group">
              <%= label_tag :Decrease_Quantity %>
              <%= number_field_tag :decreased_inventory, 0, class: "item_text", data: { 'edit-inventory-target': 'quantityMinus' }, min: 0 %>
            </div>

            <div class="input_group">
              <%= label_tag :Reason_for_Decrease %>
              <%= text_field_tag :reason_for_decrease, '', data: { 'edit-inventory-target': 'decreaseReason' } %>
            </div>
          </div>

          <div class="current_qty">New Quantity: <span class="quantity_no" data-edit-inventory-target="newQuantity"><%= @producer_variant.inventory_for_user(current_user) %></span></div>
          <div class="inventory_edit_btn">Submit</div>
        </div>

        <div class="new_qty_wrap">
          <div class="head current_qty" >
            New Quantity: <span class="quantity_no" data-edit-inventory-target="newQuantity"><%= @producer_variant.inventory_for_user(current_user) %></span>
          </div>

          <div class="btn_group">
            <%= submit_tag 'Confirm', class: 'btn bg-success text-white' %>
            <div class="btn outline_btn cancel_qty">Cancel</div>
          </div>
        </div>
       <% end %>
    </div>
  </div>
</turbo-frame>