config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"

  get '/dashboard/producer/:producer_id', to: 'dashboard#show', as: :producer_dashboard
  get '/dashboard/designer/:designer_id', to: 'dashboard#show', as: :designer_dashboard

  get 'dashboard/payment_amount_popup'

  get '/states', to: 'addresses#get_states'
  post '/close_modal/:modal_id', to: 'modals#close', as: :close_modal

  resources :products, only: [:index, :show, :new, :create,:edit, :update] do
    delete 'remove_variant', on: :member
    get 'edit_producer', on: :member
    patch 'update_producer', on: :member
  end

  resources :orders do
    member do
      get :download
      get :confirm
      get :reject
      get :send_message
      post :message_create
      get :cancel_request
      post :update_cancel_status
      get :select_variant
      get :assignee
      post :assignee_create
      get :assignee_remove_confirmation
      delete :assigne_remove
      get :on_hold_popup
      get :in_production_popup
      get :rejected_popup
      get :fullfilled_popup
      get :delete_confirmation
      get :cancel_order
      get :new_cancel_request
      post :create_cancel_request
      get :update_priority
      get :request_revision
      patch :request_revision_update
      post :create_address
      post :order_update_shipping
      delete :remove_product
      delete :remove_product_image
      delete :remove_design_files
      get :set_dimensions
      post :update_dimensions
      get :update_job_price
      patch :assigne_update_price
      get :order_slip
      get :duplicate_order
      get :edit_sender
      post :update_sender
      delete :remove_shipo_lable
      get :download_shippo_label
      post :undo
      get :save_changes_confirmation
    end

    collection do
      get :add_new_product
      get :select_variant
      get :all_producer
      get :cancel_order_index
      get :new_order_product
      post :etsy_import
    end
  end

  resources :variants do
    get :inventory, on: :collection
    get :producer_inventory, on: :member
  end

  resources :producers_variants, only: [:edit, :update] do
    member do
      get :edit_inventory
      patch :update_inventory
    end
  end

  resources :producers, only: [:edit, :update] do
    post :request_payment, on: :member
    resources :producer_variant_histories, only: [:index]
  end

  resources :designers, only: [] do
    post :request_payment, on: :member
  end

  # Sessions routes
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/etsy/authorize', to: 'etsy#authorize'
  get '/etsy/callback', to: 'etsy#callback'

  resources :payments, only: [:new, :create] do
    get :export, on: :collection
  end

  namespace :admin do
    resources :orders, only: [:index] do
      collection do
        get :on_hold
        get :rejected
        get :in_production
        get :fulfilled
      end
    end
  end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                :bigint           not null, primary key
#  brand_name        :string
#  name              :string
#  print_area_width  :bigint
#  print_area_height :bigint
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class Product < ApplicationRecord
  # Association
  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products
  has_many :variants, dependent: :destroy
  has_many :product_producer_pricings, dependent: :destroy
  has_many :shipping_labels, dependent: :destroy

  # Nested Attributes
  accepts_nested_attributes_for :variants, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :product_producer_pricings
  accepts_nested_attributes_for :shipping_labels

  # Attachements
  has_one_attached :image

  # Class Methods
  def self.search(params)
    results = all
    if params[:query].present?
      results = results.where('LOWER(products.name) LIKE ?', "%#{params[:query].downcase}%")
    end

    results.order(created_at: :desc)
  end

  def self.to_csv
    attributes = [:color, :size, :real_variant_sku, :total_inventory, :length, :height, :width, :weight_lb, :weight_oz,
                  :product_name, :brand_name]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      Variant.joins(:product).each do |variant|
        csv << attributes.map { |attr| variant.send(attr) }
      end
    end
  end

  # Instance Methods
  def to_csv
    attributes = [:color, :size, :real_variant_sku, :total_inventory, :length, :height, :width, :weight_lb, :weight_oz,
                  :product_name, :brand_name]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      variants.each do |variant|
        csv << attributes.map { |attr| variant.send(attr) }
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    per_page  = params[:per_page] || Rails.configuration.settings.default_per_page
    @products = Product.search(params).paginate(page: params[:page], per_page: per_page)

    respond_to do |format|
      format.html
      format.csv { send_data Product.to_csv, filename: "products-#{Date.today}.csv" }
      format.js do
        html_data = render_to_string(partial: "products/products_table", locals: { products: @products }, layout: false)
        render json: { html_data: html_data }
      end
    end

    if current_user.type.eql?("Producer")
      @producer = Producer.find_by(id: current_user.id)
      @pv = @producer.producers_variants.search(params)

      respond_to do |format|
        format.html
        format.js do
        html_data = render_to_string(partial: "producer_inventory", locals: { pv: @pv }, layout: false)
        render json: { html_data: html_data }
        end
      end
    end
  end

  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.csv { send_data @product.to_csv, filename: "product-#{Date.today}.csv" }
    end
  end

  def new
    @product = Product.new
    4.times { @product.shipping_labels.build }
    @producers = Producer.all

    @producers.each do |producer|
      @product
        .product_producer_pricings
        .build(producer: producer, blank_price: 0, front_side_print_price: 0, back_side_print_price: 0)
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: 'Product was successfully created.'
    else
      redirect_to new_product_path
    end
  end

  def edit
    @product   = Product.find(params[:id])
    @variants  = @product.variants.where(archive: false)
    @producers = Producer.all
  end

  def remove_variant
    @variant = Variant.find(params[:id])
    @product = @variant.product
    @variant.update(archive: true)
    # @variant.destroy
    redirect_to edit_product_path(@product), notice: 'Variant removed.'
  end

  def update
    @product = Product.find(params[:id])

    @product.shipping_labels.destroy_all    

    if @product.update(product_params)
      redirect_to products_path, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def edit_producer
    @product_producer_pricing = ProductProducerPricing.find_by(user_id: params[:user_id], product_id: params[:product_id])
    @product = Product.find(params[:product_id])
    @producer = Producer.find(params[:user_id])
  end

  def update_producer
    @product_producer_pricing = ProductProducerPricing.find_by(user_id: params[:user_id], product_id: params[:product_id])
    @product = Product.find_by(id: params[:product_id])

    if @product_producer_pricing.update(product_producer_params)
      redirect_to edit_product_path(@product), notice: 'Producer was successfully updated.'
    end
  end

  private

  def product_params
    params
      .require(:product)
      .permit(:name,
              :brand_name,
              :print_area_width,
              :print_area_height,
              :image,
              variants_attributes: [
                :color,
                :size,
                :real_variant_sku,
                :image,
                :inventory,
                :length,
                :height,
                :width,
                :weight_lb,
                :weight_oz,
                producers_variants_attributes: [
                  :id,
                  :user_id,
                  :variant_id,
                  :inventory
                ],
              ],
              product_producer_pricings_attributes: [
                :id,
                :blank_price,
                :front_side_print_price,
                :back_side_print_price,
                :user_id,
                :product_id
              ],
              shipping_labels_attributes: [
                :item_quantity_min,
                :item_quantity_max,
                :length,
                :height,
                :width,
                :weight_lb,
                :weight_oz
              ]
            )
  end

  def product_producer_params
    params.require(:product_producer_pricing).permit(:blank_price, :front_side_print_price,:back_side_print_price)
  end
end

app/views/products/_designer_index.html.erb
<div class="products_wrapper">
  <div class="products_content" data-controller="search" data-search-url-value="<%= products_path %>">
    <div class="top_section">
      <div class="search_wrap">
        <div class="search_box">
          <svg class="search_icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M17.31 15.9L20.71 19.29C20.8993 19.4778 21.0058 19.7334 21.0058 20C21.0058 20.2666 20.8993 20.5222 20.71 20.71C20.5222 20.8993 20.2666 21.0058 20 21.0058C19.7334 21.0058 19.4778 20.8993 19.29 20.71L15.9 17.31C14.5025 18.407 12.7767 19.0022 11 19C6.58172 19 3 15.4183 3 11C3 6.58172 6.58172 3 11 3C15.4183 3 19 6.58172 19 11C19.0022 12.7767 18.407 14.5025 17.31 15.9ZM11 5C7.68629 5 5 7.68629 5 11C5 14.3137 7.68629 17 11 17C14.3137 17 17 14.3137 17 11C17 7.68629 14.3137 5 11 5Z" fill="#919EAB"/>
          </svg>

          <input class="search_input" type="text" placeholder="Search Order...">
        </div>

        <div class="bell_notify">
          <div class="create_bell_box">
            <%= image_tag("ic_notifications", class: "create_bell_icon") %>

            <div class="create_notification">
              <p class="notification_text">1</p>
            </div>
          </div>

          <div class="account_icon"></div>

          <% if current_user %>
            <%= link_to 'Log Out', logout_path, method: :delete, class: "btn btn-danger" %>
          <% end %>
        </div>
      </div>

      <div class="export_btn_wrap">
        <p class="export_head">Products</p>

        <div class="btn_group">
          <a href="<%= products_path(format: :csv) %>" class="export_btn">
            <svg class="btn_icon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
              <path d="M3.33301 15.8333C3.33301 15.3731 3.7061 15 4.16634 15H15.833C16.2932 15 16.6663 15.3731 16.6663 15.8333C16.6663 16.2936 16.2932 16.6667 15.833 16.6667H4.16634C3.7061 16.6667 3.33301 16.2936 3.33301 15.8333Z" fill="white"/>
              <path d="M4.16634 16.6667C3.7061 16.6667 3.33301 16.2936 3.33301 15.8333V14.1667C3.33301 13.7064 3.7061 13.3333 4.16634 13.3333C4.62658 13.3333 4.99967 13.7064 4.99967 14.1667V15.8333C4.99967 16.2936 4.62658 16.6667 4.16634 16.6667Z" fill="white"/>
              <path d="M15.833 16.6667C15.3728 16.6667 14.9997 16.2936 14.9997 15.8333V14.1667C14.9997 13.7064 15.3728 13.3333 15.833 13.3333C16.2932 13.3333 16.6663 13.7064 16.6663 14.1667V15.8333C16.6663 16.2936 16.2932 16.6667 15.833 16.6667Z" fill="white"/>
              <path d="M9.99967 12.5C9.82691 12.5013 9.65801 12.4489 9.51634 12.35L6.18301 10C5.809 9.73468 5.71962 9.21704 5.98301 8.84167C6.11057 8.65963 6.30557 8.53609 6.52466 8.49854C6.74375 8.46098 6.96876 8.51251 7.14967 8.64167L9.99967 10.6333L12.833 8.5C13.2012 8.22386 13.7235 8.29848 13.9997 8.66667C14.2758 9.03486 14.2012 9.55719 13.833 9.83333L10.4997 12.3333C10.3554 12.4415 10.18 12.5 9.99967 12.5Z" fill="white"/>
              <path d="M9.99967 10.8333C9.53944 10.8333 9.16634 10.4602 9.16634 10V3.33333C9.16634 2.8731 9.53944 2.5 9.99967 2.5C10.4599 2.5 10.833 2.8731 10.833 3.33333V10C10.833 10.4602 10.4599 10.8333 9.99967 10.8333Z" fill="white"/>
            </svg>

            <div class="btn_text">CSV. Export</div>
          </a>

          <div class="export_btn">
            <svg class="btn_icon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
              <path d="M15.833 9.16732H10.833V4.16732C10.833 3.70708 10.4599 3.33398 9.99967 3.33398C9.53944 3.33398 9.16634 3.70708 9.16634 4.16732V9.16732H4.16634C3.7061 9.16732 3.33301 9.54041 3.33301 10.0007C3.33301 10.4609 3.7061 10.834 4.16634 10.834H9.16634V15.834C9.16634 16.2942 9.53944 16.6673 9.99967 16.6673C10.4599 16.6673 10.833 16.2942 10.833 15.834V10.834H15.833C16.2932 10.834 16.6663 10.4609 16.6663 10.0007C16.6663 9.54041 16.2932 9.16732 15.833 9.16732Z" fill="white"/>
            </svg>

            <%= link_to 'Create a New Product', new_product_path, class: 'btn_text' %>
          </div>
        </div>
      </div>
    </div>

    <div class="search_section">
      <div class="search_box">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
          <path fill-rule="evenodd" clip-rule="evenodd" d="M17.31 15.9L20.71 19.29C20.8993 19.4778 21.0058 19.7334 21.0058 20C21.0058 20.2666 20.8993 20.5222 20.71 20.71C20.5222 20.8993 20.2666 21.0058 20 21.0058C19.7334 21.0058 19.4778 20.8993 19.29 20.71L15.9 17.31C14.5025 18.407 12.7767 19.0022 11 19C6.58172 19 3 15.4183 3 11C3 6.58172 6.58172 3 11 3C15.4183 3 19 6.58172 19 11C19.0022 12.7767 18.407 14.5025 17.31 15.9ZM11 5C7.68629 5 5 7.68629 5 11C5 14.3137 7.68629 17 11 17C14.3137 17 17 14.3137 17 11C17 7.68629 14.3137 5 11 5Z" fill="#919EAB"/>
        </svg>

        <input class="search_input" value="<%= params[:query] %>" type="text" placeholder="Search Product.." data-search-target="query">
      </div>
    </div>

    <div class="table_section">
      <div class="table_content">
        <table>
          <thead>
            <tr>
              <th class="custom_col text-center"><input type="checkbox"></th>
              <th class="custom_col text-center">Product ID</th>
              <th class="custom_col text-center">Product photo</th>
              <th class="custom_col text-center">Brand Name</th>
              <th class="custom_col text-center">Product Name</th>
              <th class="custom_col text-center">Variations</th>
              <th class="custom_col text-center">Edit/Duplicate</th>
            </tr>
          </thead>

          <tbody data-search-target="results">
            <%= render 'products_table', products: @products %>
          </tbody>
        </table>
      </div>

      <div class="table_footer_wrap">
        <div class="content_btn">
          <div class="center"><input type="checkbox" /></div>

          <div class="content_text">Dense</div>
        </div>

        <%= render 'shared/pagination', records: @products, per_page: params[:per_page] %>
      </div>
    </div>
  </div>
</div>

app/views/products/_producer_address.html.erb
<span id="product-producer-address-<%= producer.id %>">
  <%= producer&.address&.fullname %>: 
  <%= producer&.address&.to_str %>
</span>

app/views/products/_producer_inventory.html.erb
<div class="inventory_panel_wrapper">
  <div class="panel_header">
    <div class="header_box">
      <div class="create_wrap">
        <% unless current_user.producer? %>
          <div class="create_content">
            <%= image_tag("ic_plus", class:"plus_icon") %>
              <%= link_to 'Create Manual Order', new_order_path , class: 'create_text'%>
          </div>
        <% end %>
        <div class="create_bell_box">
          <%= image_tag("ic_notifications", class:"create_bell_icon") %>
          <div class="create_notification">
            <p class="notification_text">1</p>
          </div>
        </div>
        <% if current_user %>
          <%= link_to 'Log Out', logout_path, method: :delete, class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="inventory_box" data-controller="search" data-search-url-value="<%= producer_inventory_variant_path(@producer) %>">
    <div class="inventory_head"><span>Inventories</span> <span><%= current_user.name %></span> </div>
    <div class="inventory_content_box">
      <%= link_to 'Click here to Track Inventory History', producer_producer_variant_histories_path(producer_id: @producer.id), class: 'history_btn' %>

      <div class="search_box">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
          <path fill-rule="evenodd" clip-rule="evenodd" d="M17.31 15.9L20.71 19.29C20.8993 19.4778 21.0058 19.7334 21.0058 20C21.0058 20.2666 20.8993 20.5222 20.71 20.71C20.5222 20.8993 20.2666 21.0058 20 21.0058C19.7334 21.0058 19.4778 20.8993 19.29 20.71L15.9 17.31C14.5025 18.407 12.7767 19.0022 11 19C6.58172 19 3 15.4183 3 11C3 6.58172 6.58172 3 11 3C15.4183 3 19 6.58172 19 11C19.0022 12.7767 18.407 14.5025 17.31 15.9ZM11 5C7.68629 5 5 7.68629 5 11C5 14.3137 7.68629 17 11 17C14.3137 17 17 14.3137 17 11C17 7.68629 14.3137 5 11 5Z" fill="#919EAB"/>
        </svg>
        <input class="search_input" value="<%= params[:query] %>" type="text" placeholder="Search Product by Name, SKU, Product ID, Color" data-search-target="query">
      </div>

      <div class="inventory_table_wrap">
        <div class="inventory_table">
          <div class="thead">
            <div class="th one">Product Id</div>
            <div class="th two">Product Image</div>
            <div class="th three">Product Name</div>
            <div class="th four">Brand</div>
            <div class="th five">SKU</div>
            <div class="th six">Color</div>
            <div class="th seven">Size</div>
            <div class="th eight">Aisle No</div>
            <div class="th nine">Status</div>
            <div class="th ten">
              <div class="inv_qty_th">
                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18" fill="none">
                  <path d="M15 9L13.9425 7.9425L9.75 12.1275V3H8.25V12.1275L4.065 7.935L3 9L9 15L15 9Z" fill="white"/>
                </svg>
                <span>Inventory QTY</span>
              </div>
            </div>
          </div>

          <div class="tbody" data-search-target="results">
            <%= render 'variants/producer_inventory_table', pv: @pv %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<turbo-frame id="edit-inventory-modal"></turbo-frame>
<turbo-frame id="edit-aisle-modal"></turbo-frame>

app/views/products/_producers_section.html.erb
<div id="producers-section" class="producers_section mb-2">
  <h5 class="producers_head">Producers</h5>

  <table class="producers_table">
    <tr>
      <th class="table_head">Producer Company Name</th>
      <th class="table_head">Producer Sender Address</th>
      <th class="table_head">Blank Price</th>
      <th class="table_head">Front Side Print Price</th>
      <th class="table_head">Back Side Print Price</th>

      <% unless f.object.new_record? %>
        <th class="table_head">Edit Pricing</th>
      <% end %>
    </tr>

    <%= f.fields_for :product_producer_pricings do |ppp| %>
      <%= ppp.hidden_field :user_id %>
      <tr>
        <td class="table_td"><%= ppp.object&.producer&.company_name %></td>
        <td class="table_td">
          <%= render 'producer_address', producer: ppp.object&.producer %>

          <a href="<%= edit_producer_path(ppp.object.producer) %>" data-turbo-frame="producer-address">
            <%= image_tag 'pencil.svg' %>
          </a>
        </td>

        <% if ppp.object.new_record? %>
          <td class="table_td">
            <%= ppp.number_field :blank_price, step: 0.01, class: 'form-control w-50 mx-auto' %>
          </td>

          <td class="table_td">
            <%= ppp.number_field :front_side_print_price, step: 0.01, class: 'form-control w-50 mx-auto' %>
          </td>

          <td class="table_td">
            <%= ppp.number_field :back_side_print_price, step: 0.01, class: 'form-control w-50 mx-auto' %>
          </td>
        <% else %>
          <td class="table_td">
            <%= ppp.object.blank_price %>
          </td>

          <td class="table_td">
            <%= ppp.object.front_side_print_price %>
          </td>

          <td class="table_td">
            <%= ppp.object.back_side_print_price %>
          </td>

          <td class="table_td edit_icon">
            <a href="<%= edit_producer_product_path(user_id: ppp.object.producer, product_id: product.id) %>" data-turbo-frame="edit_producer">
              <%= image_tag 'pencil.svg' %>
            </a>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>

  <turbo-frame id="edit_producer" class="producer_card"></turbo-frame>
  <turbo-frame id="producer-address" class="producer_card"></turbo-frame>
</div>

app/views/products/_variant_show.html.erb
<div class="col-md-9">
  <table class="table table-borderless">
    <ul>
      <% @variants.each do |variant| %>
        <li>
            <p> variant_image:</p> 
              <% if variant.image.attached? %>
                <%= image_tag variant.image %>
              <% else %>
                <%= image_tag asset_path('dummy-product.png') %>
              <% end %> 
          <p>color: <%= variant.color %></p>
          <p>size: <%= variant.size %></p>
          <p>Real_variant_SKU: <%= variant.real_variant_sku %></p>
          <p>inventory: <%= variant.total_inventory_for_user(current_user) %></p>
        </li>
      <% end %>
    </ul>
  </table>
</div>

app/views/products/edit.html.erb
<div class="hero_wrapper">
  <%= render partial: 'shared/sidebar' %>
  <div class="new_product_wrap">
    <div class="product_header">
      <svg class="search_icon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
        <path fill-rule="evenodd" clip-rule="evenodd" d="M14.425 13.25L17.2583 16.075C17.4161 16.2315 17.5048 16.4445 17.5048 16.6667C17.5048 16.8889 17.4161 17.1019 17.2583 17.2583C17.1019 17.4161 16.8889 17.5048 16.6667 17.5048C16.4445 17.5048 16.2315 17.4161 16.075 17.2583L13.25 14.425C12.0854 15.3392 10.6472 15.8352 9.16667 15.8333C5.48477 15.8333 2.5 12.8486 2.5 9.16667C2.5 5.48477 5.48477 2.5 9.16667 2.5C12.8486 2.5 15.8333 5.48477 15.8333 9.16667C15.8352 10.6472 15.3392 12.0854 14.425 13.25ZM9.16667 4.16667C6.40524 4.16667 4.16667 6.40524 4.16667 9.16667C4.16667 11.9281 6.40524 14.1667 9.16667 14.1667C11.9281 14.1667 14.1667 11.9281 14.1667 9.16667C14.1667 6.40524 11.9281 4.16667 9.16667 4.16667Z" fill="#637381"/>
      </svg>

      <div class="icon_group">
        <div class="flag"><%= image_tag("GB") %></div>

        <div class="create_bell_box">
          <%= image_tag "ic_notifications", alt: 'icon', class: "create_bell_icon" %>
          <div class="create_notification">1</div>
        </div>

        <%= image_tag "ic_user_group", alt:"icon", class:"user_icon" %>
        <%= image_tag("Img_Avatar", class: "user_icon") %>
      </div>
    </div>

    <h5 class="new_head">Edit product</h5>

    <a href="<%= product_path(@product, format: :csv) %>" class="export_btn">
      <svg class="download_icon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
        <path d="M3.33301 15.8333C3.33301 15.3731 3.7061 15 4.16634 15H15.833C16.2932 15 16.6663 15.3731 16.6663 15.8333C16.6663 16.2936 16.2932 16.6667 15.833 16.6667H4.16634C3.7061 16.6667 3.33301 16.2936 3.33301 15.8333Z" fill="white"/>
        <path d="M4.16634 16.6667C3.7061 16.6667 3.33301 16.2936 3.33301 15.8333V14.1667C3.33301 13.7064 3.7061 13.3333 4.16634 13.3333C4.62658 13.3333 4.99967 13.7064 4.99967 14.1667V15.8333C4.99967 16.2936 4.62658 16.6667 4.16634 16.6667Z" fill="white"/>
        <path d="M15.833 16.6667C15.3728 16.6667 14.9997 16.2936 14.9997 15.8333V14.1667C14.9997 13.7064 15.3728 13.3333 15.833 13.3333C16.2932 13.3333 16.6663 13.7064 16.6663 14.1667V15.8333C16.6663 16.2936 16.2932 16.6667 15.833 16.6667Z" fill="white"/>
        <path d="M9.99967 12.5C9.82691 12.5013 9.65801 12.4489 9.51634 12.35L6.18301 10C5.809 9.73468 5.71962 9.21704 5.98301 8.84167C6.11057 8.65963 6.30557 8.53609 6.52466 8.49854C6.74375 8.46098 6.96876 8.51251 7.14967 8.64167L9.99967 10.6333L12.833 8.5C13.2012 8.22386 13.7235 8.29848 13.9997 8.66667C14.2758 9.03486 14.2012 9.55719 13.833 9.83333L10.4997 12.3333C10.3554 12.4415 10.18 12.5 9.99967 12.5Z" fill="white"/>
        <path d="M9.99967 10.8333C9.53944 10.8333 9.16634 10.4602 9.16634 10V3.33333C9.16634 2.8731 9.53944 2.5 9.99967 2.5C10.4599 2.5 10.833 2.8731 10.833 3.33333V10C10.833 10.4602 10.4599 10.8333 9.99967 10.8333Z" fill="white"/>
      </svg>

      <div class="btn_text">CSV. Export</div>
    </a>

    <%= render 'form', product: @product, variants: @variants %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $(".icon_delete").click(function(){
      $(".delete_variation").toggleClass("hide");
    });
  });
</script>

app/views/products/edit_producer.html.erb
<turbo-frame id="edit_producer" class="producer_card">
  <%= form_for @product_producer_pricing, url: update_producer_product_path(user_id: @producer, product_id: @product), method: :patch do |f| %>
    <div class="producer_card">
      <h5 class="producer_head">Pricing (Production cost)</h5>
      <div class="card_content">
        <div class="card_items">
          <p class="cart_text">Blank price</p>
          <div class="cost_wrap">
            <label>Cost of Printing</label>
            <span>$</span>
            <%= f.text_field :blank_price %>
          </div>
        </div>
        <div class="card_items">
          <p class="cart_text">Front side print price</p>
          <div class="cost_wrap">
            <label>Cost of Printing</label>
            <span>$</span>
            <%= f.text_field :front_side_print_price %>
          </div>
        </div>
        <div class="card_items">
          <p class="cart_text">Back side print price</p>
          <div class="cost_wrap">
            <label>Cost of Printing</label>
            <span>$</span>
            <%= f.text_field :back_side_print_price %>
          </div>
        </div>
      </div>
      <div class="bottom_btn_group">
        <%= link_to 'Cancel', edit_product_path(@product), class: 'btn btn-secondary' %>
        <%= f.submit 'Save', data: { 'turbo-frame': '_top' }, class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</turbo-frame>